name: Deploy Python App to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sanjit-we
  PYTHON_VERSION: '3.10'                 
  REQUIREMENTS_FILE: requirements.txt   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Debugging step (optional, helps find file paths)
      - name: Debug current directory
        run: |
          pwd
          ls -R

      # Create venv and install dependencies
      - name: Install dependencies
        run: |
          python -m venv antenv

